server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
      - id: service_person
        uri: http://localhost:8008/
        predicates:
        - Path=/person/**
      - id: service_account
        uri: http://localhost:8070/
        predicates:
        - Path=/account/**
