server:
  port: 8082

spring:
  application:
     name: cloudgateway
# routing for service 1
zuul:
  routes:
    service_1:
       path: /api/service_1/**
    service_1:
       url: http://localhost:8008/
# routing for service 2
    service_2:
       path: /api/service_2/**
    service_2:
       url: http://localhost:8070/  
