server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
      - id: service_person
        uri: http://localhost:8080/
        predicates:
        - Path=/employee/**
      - id: service_account
        uri: http://localhost:8070/
        predicates:
        - Path=/consumer/**
