server:
    port: ${PORT:8080}
message: Person configuration server is alive!
spring:
   cloud: 
     config: 
        uri:http://localhost:8888
     profiles:
        active:database
managment: 
   endpoints:
       web: 
         exposure: 
             include:*
